plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  tag:app-stack-name: APP_STACK_NAME
  tag:environment: dev
  tag:swarm-role: worker
hostnames:
  - "private-ip-address"
compose:
<<<<<<< HEAD
  ansible_user: "'ec2-user'"
=======
  ansible_user: "'ec2-user'"
>>>>>>> f35c98795b368f2519eafdfc4b5927169e5c247e
